from typing import Final

EXTNAME: Final[str] = "SPECTRUM"
HDUCLASS: Final[str] = "OGIP"
HDUCLAS1: Final[str] = "SPECTRUM"
HDUVERS1: Final[str] = "1.1.0"
HDUVERS: Final[str] = "1.1.0"
HDUCLAS2: Final[str] = "TOTAL"
HDUCLAS3: Final[str] = "COUNT"
TLMIN1: Final[str] = "0"
TLMAX1: Final[str] = "1023"
TELESCOP: Final[str] = "CHANDRAYAAN-2"
INSTRUME: Final[str] = "CLASS"
FILTER: Final[str] = "none"
EXPOSURE: Final[str] = "16"
AREASCAL: Final[str] = "1.0"
BACKFILE: Final[str] = "NONE"
BACKSCAL: Final[str] = "1.0"
CORRFILE: Final[str] = "NONE"
CORRSCAL: Final[str] = "1.0"
RESPFILE: Final[str] = "class_rmf_v1.rmf"
ANCRFILE: Final[str] = "class_arf_v1.arf"
PHAVERSN: Final[str] = "1992a"
DETCHANS: Final[str] = "1024"
CHANTYPE: Final[str] = "PHA"
POISSERR: Final[str] = "True"
STAT_ERR: Final[str] = "0"
SYS_ERR: Final[str] = "0"
GROUPING: Final[str] = "0"
QUALITY: Final[str] = "0"
EQUINOX: Final[str] = "2000.0"
DATE: Final[str] = "Thu Mar 17 17:41:51 2022"
PROGRAM: Final[str] = "generate_spectrum_from_spectrogram.pro"
STARTIME: Final[str] = "STARTIME"
ENDTIME: Final[str] = "ENDTIME"
GAIN: Final[str] = "27.0"
SCD_USED: Final[str] = "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"
MID_UTC: Final[str] = "2021-08-27T21:03:24.000"
SAT_ALT: Final[str] = "113.779"
SAT_LAT: Final[str] = "-13.7739"
SAT_LON: Final[str] = "-123.762"
LST_HR: Final[str] = "7"
LST_MIN: Final[str] = "46"
LST_SEC: Final[str] = "48"
BORE_LAT: Final[str] = "BORE_LAT"
BORE_LON: Final[str] = "BORE_LON"
V0_LAT: Final[str] = "V0_LAT" # upper left
V1_LAT: Final[str] = "V1_LAT" # lower left
V2_LAT: Final[str] = "V2_LAT" # lower right
V3_LAT: Final[str] = "V3_LAT" # upper right

V0_LON: Final[str] = "V0_LON" # upper left
V1_LON: Final[str] = "V1_LON" # lower left
V2_LON: Final[str] = "V2_LON" # lower right
V3_LON: Final[str] = "V3_LON" # upper right
SOLARANG: Final[str] = "SOLARANG"
PHASEANG: Final[str] = "PHASEANG"
EMISNANG: Final[str] = "EMISNANG"
