package constants

const STEP1_CHECKS_JOB_QUEUE = "STEP1_CHECKS_JOB_QUEUE"
const STEP2_XRF_LINE_INTENSITY_JOB_QUEUE = "STEP2_XRF_LINE_INTENSITY_JOB_QUEUE"
const STEP3_PREDICTION_JOB_QUEUE = "STEP3_PREDICTION_JOB_QUEUE"
const STEP4_X2_ABUND_JOB_QUEUE = "STEP4_X2_ABUND_JOB_QUEUE"
const STEP5_SR_JOB_QUEUE = "STEP5_SR_JOB_QUEUE"
const CREATE_JOB_QUEUE = "CREATE_JOB_QUEUE"
